spring.application.name=backendTaller4

spring.datasource.url=jdbc:postgresql://localhost:5432/taller4
spring.datasource.username=postgres
spring.datasource.password=Franco1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

jwt.secret=MiClaveSuperSecretaYLoSuficientementeLargaParaHS256_2026!
jwt.expiration=86400000