spring.application.name=backendTaller4

spring.datasource.url=jdbc:h2:mem:mydatabase 

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Guarda la base de datos en un archivo local en la carpeta del proyecto
spring.datasource.url=jdbc:h2:file:./data/taller4db

# Mantiene las tablas creadas por JPA sin borrarlas al reiniciar
spring.jpa.hibernate.ddl-auto=update