spring.application.name=backend

# Configuración de la base de datos H2 en memoria
spring.datasource.url=jdbc:h2:mem:inscripcionesdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=admin
spring.datasource.password=admin
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Actualiza el esquema de la base de datos automáticamente
spring.jpa.hibernate.ddl-auto=update

# Habilitar la consola H2 en el navegador (http://localhost:8080/h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Mostrar las consultas SQL en la consola (útil para desarrollo)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true